import { cmd } from 'elm-ts/lib'
import { Cmd } from 'elm-ts/lib/Cmd'
import { Html } from 'elm-ts/lib/React'
import { perform } from 'elm-ts/lib/Task'
import { Task } from 'fp-ts/lib/Task'
import * as React from 'react'
import { assertNever } from './assertNever'